config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('templating.urls', namespace='templating'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templating/urls.py
from django.urls import path
from templating.views import contacts_page, increase_views, BlogListView, BlogCreateView, HomeListView, BlogUpdateView, BlogDeleteView, BlogDetailView
from templating.apps import TemplatingConfig

app_name = TemplatingConfig.name

urlpatterns = [
    path('', HomeListView.as_view(), name='home'),
    path('contacts/', contacts_page, name='contacts'),

    path('blog/', BlogListView.as_view(), name='blog'),
    path('blog_create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog_update/<int:pk>/<slug>/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog_delete/<int:pk>/<slug>/', BlogDeleteView.as_view(), name='blog_delete'),
    path('blog_detail/<int:pk>/<slug>/', BlogDetailView.as_view(), name='blog_detail'),
    path('inc_views/<int:pk>/<slug>/', increase_views, name='inc_views')
]

templating/models.py
from django.db import models
from transliterate import slugify


class Items(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    price = models.IntegerField(verbose_name='Цена')
    description_1 = models.CharField(max_length=100, verbose_name='Описание 1')
    description_2 = models.CharField(max_length=100, verbose_name='Описание 2')
    description_3 = models.CharField(max_length=100, verbose_name='Описание 3')
    description_4 = models.CharField(max_length=100, verbose_name='Описание 4')

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return f'{self.name} {self.price} {self.description_1} {self.description_2} {self.description_3} {self.description_4}'


class Blog(models.Model):
    STATUS_ACTIVE = 'True'
    STATUS_INACTIVE = 'False'
    STATUSES = (
        (STATUS_ACTIVE, 'положительный'),
        (STATUS_INACTIVE, 'отрицательный')
    )

    id = models.AutoField(primary_key=True, verbose_name='id')
    heading = models.CharField(max_length=250, verbose_name='Заголовк')
    slug = models.CharField(max_length=250, unique=True, verbose_name='slug')
    content = models.CharField(max_length=250, verbose_name='Содержимое')
    image = models.FileField(verbose_name='Изображение', null=True)
    create_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(choices=STATUSES, default=STATUS_ACTIVE, max_length=15)
    view = models.IntegerField(verbose_name='Просмотры', default=0)

    def save(self, *args, **kwargs):
        self.slug = slugify(str(self.heading))
        super(Blog, self).save(*args, **kwargs)

templating/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from templating.models import Items, Blog


def increase_views(request, pk, slug):
    blog_items = get_object_or_404(Blog, pk=pk, slug=slug)
    blog_items.view += 1
    blog_items.save()
    return redirect(reverse(f'templating:blog_detail/{str(pk)}/{slug}/'))


class BlogListView(ListView):
    model = Blog


class HomeListView(ListView):
    model = Items


class BlogCreateView(CreateView):
    model = Blog
    fields = ('heading', 'content', 'image')
    success_url = reverse_lazy('templating:blog')


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('heading', 'content', 'image', 'status')
    success_url = reverse_lazy('templating:blog')


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('templating:blog')


class BlogDetailView(DetailView):
    model = Blog
    fields = ('heading', 'content', 'image')


def contacts_page(request):
    return render(request, 'templating/contacts.html')


templating/templates/templating/base.html
{% load static %}
{% load mediapath from template_filters %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<style>
        body {
            background-image: url("{% mediapath '1.jpg' %}");
<!--            background-image: url("{{ '1.jpg'|mediapath }}");-->
             }
</style>
<body>
{% include 'templating/includes/inc_main_menu.html' %}
{% block content %}
{% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templating/templates/templating/blog_confirm_delete.html
{% extends 'templating/base.html'%}
{% block content %}
<div class="container">
    <div class="col-5">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <p><h5> Вы действительно хотите удалить статью {{object.name}}? </h5></p>
                <a class="p-2 btn btn-primary"
                   href="{% url 'templating:blog_detail' object.pk object.slug %}">Отменить</a>
                <button class="p-2 btn btn-outline-danger bg-primary-subtle" type="submit">Удалить</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templating/templates/templating/blog_detail.html
{% extends 'templating/base.html'%}
{% block content %}
<div class="'container">
    <div class="col-4" style="margin:0 auto;">
        <div class="card" style="margin:0 auto;">
            <img src="{{object.image.url}}" class="card-img-top">
            <div class="card-body">
                <h5 class="card-title">{{object.heading}}</h5>
                <p class="card-text">{{object.content}}</p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">{{object.create_date}}</li>
                <li class="list-group-item">{{object.view}}</li>
            </ul>
            <div class="card-body">
                <a href="{% url 'templating:blog_update' object.pk object.slug %}" class="btn btn-info">Update</a>
                <a href="{% url 'templating:blog_delete' object.pk object.slug %}" class="btn btn-danger">Delete</a>
                <a href="{% url 'templating:blog' %}" class="btn btn-primary">< Back</a>
            </div>
        </div>
    </div>
    {% endblock %}

templating/templates/templating/blog_form.html
{% extends 'templating/base.html'%}
{% block content %}
<div class="container">
    <div class="col-5">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="p-2 btn btn-outline-primary bg-primary-subtle" type="submit">Отправить</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templating/templates/templating/blog_list.html
{% extends 'templating/base.html'%}
{% block content %}
<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        {% if object.status == 'True' %}
        <div class="col-4">
            <div class="card" style="width: 18rem;">
                <img src="{{object.image.url}}" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">{{object.heading}}</h5>
                    <p class="card-text">{{object.content}}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">{{object.create_date}}</li>
                    <li class="list-group-item">{{object.view}}</li>
                </ul>
                <div class="card-body">
                    <a href="{% url 'templating:blog_detail' object.pk object.slug %}" class="btn btn-outline-success bg-primary-subtle">Просмотр</a>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
    {% endblock %}

templating/templates/templating/contacts.html
{% extends 'templating/base.html'%}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <div class="mb-3">
                            <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templating/templates/templating/home.html
{% extends 'templating/base.html'%}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{object.name}}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">$ {{object.price}}</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- {{object.description_1}}</li>
                        <li>- {{object.description_2}}</li>
                        <li>- {{object.description_3}}</li>
                        <li>- {{object.description_4}}</li>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

templating/templates/templating/includes/inc_main_menu.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'templating:home' %}">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'templating:contacts' %}">Контакты</a>
        <a class="p-2 btn btn-outline-primary bg-white" href="{% url 'templating:blog' %}">Блог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'templating:blog_create' %}">Создать блог</a>
    </nav>
</div>

templating/templates/templating/items_list.html
{% extends 'templating/base.html'%}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{object.name}}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">$ {{object.price}}</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- {{object.description_1}}</li>
                        <li>- {{object.description_2}}</li>
                        <li>- {{object.description_3}}</li>
                        <li>- {{object.description_4}}</li>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}